import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader, StatusBadge, adminStyles as styles, statusTone } from "@/components/admin/AdminUi";
import { formatAdminDate, formatMoney } from "@/lib/admin/format";
import { adminStatusLabel, getAdminLocale, localizedText } from "@/lib/admin/i18n";
import { getCurrency, getCustomer } from "@/lib/admin/repository";

export default async function CustomerDetailPage({ params }: { params: Promise<{ locale: string; id: string }> }) {
  const { locale: value, id } = await params; const locale = getAdminLocale(value); const [customer, currency] = await Promise.all([getCustomer(id), getCurrency()]); if (!customer) notFound();
  return <><PageHeader title={customer.name} description={`${locale === "ar" ? "عميل منذ" : "Customer since"} ${formatAdminDate(customer.joinedAt, locale)}`} actions={<Link className={styles.buttonSecondary} href={`/${locale}/admin/customers`}>{locale === "ar" ? "العودة للعملاء" : "Back to customers"}</Link>} />
    <section className={`${styles.grid} ${styles.metrics}`}><article className={styles.card}><span className={styles.metricLabel}>{locale === "ar" ? "البريد" : "Email"}</span><strong className={styles.primaryCell} dir="ltr">{customer.email}</strong></article><article className={styles.card}><span className={styles.metricLabel}>{locale === "ar" ? "الهاتف" : "Phone"}</span><strong className={styles.primaryCell} dir="ltr">{customer.phone}</strong></article><article className={styles.card}><span className={styles.metricLabel}>{locale === "ar" ? "عدد الطلبات" : "Orders"}</span><strong className={styles.metricValue}>{customer.orderCount}</strong></article><article className={styles.card}><span className={styles.metricLabel}>{locale === "ar" ? "إجمالي الإنفاق" : "Fulfilled spending"}</span><strong className={styles.metricValue}>{formatMoney(customer.totalSpent, locale, currency)}</strong></article></section>
    <section className={`${styles.grid} ${styles.twoColumn} ${styles.sectionGap}`}><article className={styles.card}><div className={styles.cardHeader}><div><h2>{locale === "ar" ? "الطلبات" : "Orders"}</h2></div></div>{customer.orders.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{locale === "ar" ? "الطلب" : "Order"}</th><th>{locale === "ar" ? "التاريخ" : "Date"}</th><th>{locale === "ar" ? "الحالة" : "Status"}</th><th>{locale === "ar" ? "الإجمالي" : "Total"}</th></tr></thead><tbody>{customer.orders.map((order) => <tr key={order.id}><td><Link href={`/${locale}/admin/orders/${order.id}`}>{order.orderNumber}</Link></td><td>{formatAdminDate(order.createdAt, locale)}</td><td><StatusBadge label={adminStatusLabel(locale, order.status)} tone={statusTone(order.status)} /></td><td>{formatMoney(order.total, locale, order.currency)}</td></tr>)}</tbody></table></div> : <div className={styles.emptyState}><p>{locale === "ar" ? "لم يقدم هذا العميل طلبًا بعد." : "This customer has not ordered yet."}</p></div>}</article>
    <article className={styles.card}><div className={styles.cardHeader}><div><h2>{locale === "ar" ? "العناوين المحفوظة" : "Saved addresses"}</h2></div></div>{customer.addresses.length ? <div className={styles.stack}>{customer.addresses.map((address) => <article className={styles.card} key={address.id}><strong>{address.label || address.recipientName}</strong><p>{localizedText(locale, address.cityAr, address.cityEn)} · {localizedText(locale, address.areaAr, address.areaEn)}</p><p>{address.addressLine}</p>{address.locationDetails ? <p className={styles.helpText}>{address.locationDetails}</p> : null}<span dir="ltr">{address.phone}</span></article>)}</div> : <div className={styles.emptyState}><p>{locale === "ar" ? "لا توجد عناوين محفوظة." : "No saved addresses."}</p></div>}</article></section>
  </>;
}
