import Link from "next/link";
import { notFound } from "next/navigation";
import { OrderActions } from "@/components/admin/OrderActions";
import { PageHeader, StatusBadge, adminStyles as styles, statusTone } from "@/components/admin/AdminUi";
import { formatAdminDate, formatMoney } from "@/lib/admin/format";
import { adminStatusLabel, getAdminLocale, localizedText } from "@/lib/admin/i18n";
import { getOrder } from "@/lib/admin/repository";

export default async function OrderDetailPage({ params }: { params: Promise<{ locale: string; id: string }> }) {
  const { locale: value, id } = await params; const locale = getAdminLocale(value); const order = await getOrder(id); if (!order) notFound();
  const fulfillment = order.fulfillmentMethod === "DELIVERY" ? (locale === "ar" ? "توصيل" : "Delivery") : (locale === "ar" ? "استلام من المتجر" : "In-store pickup");
  return <><PageHeader title={`${locale === "ar" ? "الطلب" : "Order"} ${order.orderNumber}`} description={`${formatAdminDate(order.createdAt, locale, true)} · ${fulfillment}`} actions={<><Link className={styles.buttonSecondary} href={`/${locale}/admin/orders`}>{locale === "ar" ? "العودة للطلبات" : "Back to orders"}</Link><Link className={styles.button} href={`/${locale}/admin/orders/${order.id}/print`}>{locale === "ar" ? "ورقة الطباعة" : "Print sheet"}</Link></>} />
    <div className={`${styles.grid} ${styles.twoColumn}`}><div className={styles.stack}>
      <section className={styles.card}><div className={styles.cardHeader}><div><h2>{locale === "ar" ? "تفاصيل العميل والتسليم" : "Customer & fulfillment"}</h2></div><div className={styles.row}><StatusBadge label={adminStatusLabel(locale, order.status)} tone={statusTone(order.status)} /><StatusBadge label={adminStatusLabel(locale, order.paymentStatus)} tone={statusTone(order.paymentStatus)} /></div></div><dl className={styles.details}><Detail label={locale === "ar" ? "الاسم" : "Name"} value={order.customerName} /><Detail label={locale === "ar" ? "الهاتف" : "Phone"} value={order.customerPhone} dir="ltr" /><Detail label={locale === "ar" ? "البريد" : "Email"} value={order.customerEmail ?? "—"} dir="ltr" /><Detail label={locale === "ar" ? "طريقة الاستلام" : "Fulfillment"} value={fulfillment} /><Detail label={locale === "ar" ? "المدينة" : "City"} value={localizedText(locale, order.cityNameAr, order.cityNameEn)} /><Detail label={locale === "ar" ? "المنطقة" : "Area"} value={localizedText(locale, order.areaNameAr, order.areaNameEn)} /><Detail label={locale === "ar" ? "العنوان" : "Address"} value={order.address ?? "—"} /><Detail label={locale === "ar" ? "وصف الموقع" : "Location details"} value={order.locationDescription ?? "—"} /></dl>{order.notes ? <div className={`${styles.infoBanner} ${styles.sectionGap}`}><strong>{locale === "ar" ? "ملاحظة العميل:" : "Customer note:"}</strong> {order.notes}</div> : null}</section>
      <section className={styles.card}><div className={styles.cardHeader}><div><h2>{locale === "ar" ? "المنتجات" : "Items"}</h2></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{locale === "ar" ? "المنتج" : "Product"}</th><th>SKU</th><th>{locale === "ar" ? "السعر" : "Price"}</th><th>{locale === "ar" ? "الكمية" : "Qty"}</th><th>{locale === "ar" ? "الإجمالي" : "Line total"}</th></tr></thead><tbody>{order.items.map((item) => <tr key={item.id}><td className={styles.primaryCell}>{localizedText(locale, item.productNameAr, item.productNameEn)}{item.variantLabelAr || item.variantLabelEn ? <span className={styles.secondaryText}>{localizedText(locale, item.variantLabelAr, item.variantLabelEn)}</span> : null}</td><td dir="ltr">{item.sku}</td><td>{formatMoney(item.unitPrice, locale, order.currency)}</td><td>{item.quantity}</td><td>{formatMoney(item.lineTotal, locale, order.currency)}</td></tr>)}</tbody><tfoot><tr><th colSpan={4}>{locale === "ar" ? "المجموع الفرعي" : "Subtotal"}</th><td>{formatMoney(order.subtotal, locale, order.currency)}</td></tr><tr><th colSpan={4}>{locale === "ar" ? "رسوم التوصيل" : "Delivery fee"}</th><td>{formatMoney(order.deliveryFee, locale, order.currency)}</td></tr><tr><th colSpan={4}>{locale === "ar" ? "المبلغ النهائي" : "Final total"}</th><td><strong>{formatMoney(order.total, locale, order.currency)}</strong></td></tr></tfoot></table></div><p className={styles.helpText}>{locale === "ar" ? "تم قبول السياسات في" : "Policies accepted at"} {formatAdminDate(order.policyAcceptedAt, locale, true)}</p></section>
    </div><div className={styles.stack}><OrderActions id={order.id} locale={locale} status={order.status} paymentStatus={order.paymentStatus} fulfillment={order.fulfillmentMethod} /><section className={styles.card}><div className={styles.cardHeader}><div><h2>{locale === "ar" ? "سجل الحالة" : "Status history"}</h2></div></div>{order.history.length ? <ol className={styles.timeline}>{order.history.map((entry) => <li className={styles.timelineItem} key={entry.id}><strong>{adminStatusLabel(locale, entry.toStatus)}</strong><p>{formatAdminDate(entry.createdAt, locale, true)} · {entry.changedBy}</p>{entry.note ? <p>{entry.note}</p> : null}</li>)}</ol> : <div className={styles.emptyState}><p>{locale === "ar" ? "لا توجد تغييرات مسجلة بعد." : "No status changes recorded yet."}</p></div>}</section></div></div>
  </>;
}
function Detail({ label, value, dir }: { label: string; value: string; dir?: "ltr" | "rtl" }) { return <div><dt>{label}</dt><dd dir={dir}>{value}</dd></div>; }
