import Link from "next/link";
import { ReportSalesChart } from "@/components/admin/DashboardCharts";
import { ReportExportButtons } from "@/components/admin/ReportExportButtons";
import { EmptyState, MetricCard, PageHeader, adminStyles as styles } from "@/components/admin/AdminUi";
import { formatAdminDate, formatMoney } from "@/lib/admin/format";
import { getAdminLocale, localizedText } from "@/lib/admin/i18n";
import { getCurrency, listCategories } from "@/lib/admin/repository";
import type { AdminReportData } from "@/lib/admin/types";
import { reportQuerySchema } from "@/lib/admin/schemas";
import { getReportData } from "@/lib/reports/service";

type Query = { from?: string; to?: string; status?: string; categoryId?: string; fulfillment?: string; payment?: string; paymentStatus?: string; group?: string };
export default async function ReportsPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<Query> }) {
  const locale = getAdminLocale((await params).locale); const query = await searchParams; const parsed = reportQuerySchema.safeParse(query); const [report, currency, categories] = await Promise.all([getReportData(parsed.success ? parsed.data : {}), getCurrency(), listCategories()]); const exportQuery = new URLSearchParams({ from: report.from, to: report.to, status: report.status, categoryId: report.categoryId, fulfillment: report.fulfillment, payment: report.payment, paymentStatus: report.paymentStatus, group: report.group, locale });
  const words = locale === "ar" ? { title: "التقارير والتحليلات", description: "تقارير واضحة من بيانات المتجر مع نطاق تاريخ وحالة قابلة للتغيير.", revenue: "الإيراد ضمن التصفية", orders: "الطلبات ضمن التصفية", average: "متوسط قيمة الطلب", fulfilled: "مكتملة", cancelled: "ملغاة", delivery: "توصيل", pickup: "استلام", customers: "العملاء المسجلون", newCustomers: "عملاء جدد", returning: "عملاء عائدون", carts: "سلات غير مكتملة", trend: "اتجاه المبيعات", products: "أداء المنتجات", categories: "المبيعات حسب التصنيف", customerReport: "أفضل العملاء", insights: "مؤشرات العمل", filter: "تطبيق", clear: "آخر 30 يومًا", export: "تصدير تقرير المنتجات CSV" } : { title: "Reports & analytics", description: "Clear reports from store data with adjustable date and status filters.", revenue: "Filtered revenue", orders: "Filtered orders", average: "Average order value", fulfilled: "Fulfilled", cancelled: "Cancelled", delivery: "Delivery", pickup: "Pickup", customers: "Registered customers", newCustomers: "New customers", returning: "Returning customers", carts: "Unconverted carts", trend: "Sales trend", products: "Product performance", categories: "Sales by category", customerReport: "Top customers", insights: "Business insights", filter: "Apply", clear: "Last 30 days", export: "Export product report CSV" };
  const productName = (product: AdminReportData["products"][number] | undefined) => product ? localizedText(locale, product.nameAr, product.nameEn) : (locale === "ar" ? "لا توجد بيانات" : "No data");
  const byUnits = [...report.products].sort((left, right) => right.units - left.units);
  const byViews = [...report.products].sort((left, right) => right.views - left.views);
  const byWishlists = [...report.products].sort((left, right) => right.wishlists - left.wishlists);
  const byCarts = [...report.products].sort((left, right) => right.cartAdds - left.cartAdds);
  const cartNotOrdered = byCarts.find((product) => product.cartAdds > 0 && product.units === 0);
  const lowStock = report.products.filter((product) => product.stock > 0 && product.stock <= product.lowStockThreshold).length;
  const outOfStock = report.products.filter((product) => product.stock <= 0).length;
  const inactiveCutoff = Date.parse(`${report.to}T23:59:59.999Z`) - 90 * 86_400_000;
  return <><PageHeader title={words.title} description={words.description} actions={<ReportExportButtons locale={locale} baseQuery={exportQuery.toString()} />} />
    <form className={styles.toolbar} method="get">
      <div className={styles.field}><label htmlFor="report-from">{locale === "ar" ? "من تاريخ" : "From"}</label><input id="report-from" name="from" className={styles.input} type="date" defaultValue={report.from} /></div>
      <div className={styles.field}><label htmlFor="report-to">{locale === "ar" ? "إلى تاريخ" : "To"}</label><input id="report-to" name="to" className={styles.input} type="date" defaultValue={report.to} /></div>
      <div className={styles.field}><label htmlFor="report-status">{locale === "ar" ? "حالة الطلب" : "Order status"}</label><select id="report-status" name="status" className={styles.select} defaultValue={report.status}><option value="FULFILLED">{locale === "ar" ? "تم التوصيل أو الاستلام" : "Delivered or collected"}</option><option value="NEW">{locale === "ar" ? "جديد" : "New"}</option><option value="CONFIRMED">{locale === "ar" ? "مؤكد" : "Confirmed"}</option><option value="PREPARING">{locale === "ar" ? "قيد التجهيز" : "Preparing"}</option><option value="READY_FOR_DELIVERY">{locale === "ar" ? "جاهز للتوصيل" : "Ready for delivery"}</option><option value="SENT_TO_DELIVERY_COMPANY">{locale === "ar" ? "أرسل لشركة التوصيل" : "Sent to delivery company"}</option><option value="DELIVERED">{locale === "ar" ? "تم التوصيل" : "Delivered"}</option><option value="READY_FOR_PICKUP">{locale === "ar" ? "جاهز للاستلام" : "Ready for pickup"}</option><option value="COLLECTED">{locale === "ar" ? "تم الاستلام" : "Collected"}</option><option value="CANCELLED">{locale === "ar" ? "ملغى" : "Cancelled"}</option><option value="ALL">{locale === "ar" ? "كل الحالات" : "All statuses"}</option></select></div>
      <div className={styles.field}><label htmlFor="report-category">{locale === "ar" ? "التصنيف" : "Category"}</label><select id="report-category" name="categoryId" className={styles.select} defaultValue={report.categoryId}><option value="">{locale === "ar" ? "كل التصنيفات" : "All categories"}</option>{categories.map((category) => <option key={category.id} value={category.id}>{localizedText(locale, category.nameAr, category.nameEn)}</option>)}</select></div>
      <div className={styles.field}><label htmlFor="report-fulfillment">{locale === "ar" ? "طريقة التسليم" : "Fulfillment"}</label><select id="report-fulfillment" name="fulfillment" className={styles.select} defaultValue={report.fulfillment}><option value="ALL">{locale === "ar" ? "الكل" : "All"}</option><option value="DELIVERY">{locale === "ar" ? "توصيل" : "Delivery"}</option><option value="PICKUP">{locale === "ar" ? "استلام" : "Pickup"}</option></select></div>
      <div className={styles.field}><label htmlFor="report-payment">{locale === "ar" ? "طريقة الدفع" : "Payment"}</label><select id="report-payment" name="payment" className={styles.select} defaultValue={report.payment}><option value="ALL">{locale === "ar" ? "الكل" : "All"}</option><option value="CASH_ON_DELIVERY">{locale === "ar" ? "نقدًا عند التوصيل" : "Cash on delivery"}</option><option value="CASH_ON_PICKUP">{locale === "ar" ? "نقدًا عند الاستلام" : "Cash on pickup"}</option></select></div>
      <div className={styles.field}><label htmlFor="report-payment-status">{locale === "ar" ? "حالة الدفع" : "Payment status"}</label><select id="report-payment-status" name="paymentStatus" className={styles.select} defaultValue={report.paymentStatus}><option value="ALL">{locale === "ar" ? "الكل" : "All"}</option><option value="PENDING">{locale === "ar" ? "قيد الانتظار" : "Pending"}</option><option value="PAID">{locale === "ar" ? "مدفوع" : "Paid"}</option><option value="CANCELLED">{locale === "ar" ? "ملغي" : "Cancelled"}</option></select></div>
      <div className={styles.field}><label htmlFor="report-group">{locale === "ar" ? "تجميع الاتجاه" : "Trend grouping"}</label><select id="report-group" name="group" className={styles.select} defaultValue={report.group}><option value="day">{locale === "ar" ? "يومي" : "Daily"}</option><option value="week">{locale === "ar" ? "أسبوعي" : "Weekly"}</option><option value="month">{locale === "ar" ? "شهري" : "Monthly"}</option></select></div>
      <button className={styles.button} type="submit">{words.filter}</button><Link className={styles.buttonSecondary} href={`/${locale}/admin/reports`}>{words.clear}</Link>
    </form>
    <section className={`${styles.grid} ${styles.metrics}`} aria-label={locale === "ar" ? "ملخص التقرير" : "Report summary"}><MetricCard label={words.revenue} value={formatMoney(report.metrics.revenue, locale, currency)} tone="success" /><MetricCard label={words.orders} value={String(report.metrics.orderCount)} /><MetricCard label={words.average} value={formatMoney(report.metrics.averageOrderValue, locale, currency)} /><MetricCard label={locale === "ar" ? "طلبات موصلة" : "Delivered orders"} value={String(report.metrics.deliveredOrders)} tone="success" /><MetricCard label={locale === "ar" ? "طلبات مستلمة" : "Collected orders"} value={String(report.metrics.collectedOrders)} tone="success" /><MetricCard label={words.cancelled} value={String(report.metrics.cancelledOrders)} tone={report.metrics.cancelledOrders ? "warning" : "default"} /><MetricCard label={words.delivery} value={String(report.metrics.deliveryOrders)} /><MetricCard label={words.pickup} value={String(report.metrics.pickupOrders)} /><MetricCard label={words.customers} value={String(report.metrics.registeredCustomers)} /><MetricCard label={words.newCustomers} value={String(report.metrics.newCustomers)} /><MetricCard label={words.returning} value={String(report.metrics.returningCustomers)} /><MetricCard label={words.carts} value={String(report.metrics.abandonedCarts)} tone={report.metrics.abandonedCarts ? "warning" : "default"} /></section>
    <section className={`${styles.card} ${styles.sectionGap}`}><div className={styles.cardHeader}><div><h2>{words.trend}</h2><p>{report.from} — {report.to}</p></div></div><ReportSalesChart data={report.salesSeries} locale={locale} currency={currency} /></section>
    <section className={`${styles.card} ${styles.sectionGap}`} id="product-report"><div className={styles.cardHeader}><div><h2>{words.products}</h2><p>{locale === "ar" ? "المبيعات والمشاهدات والحفظ والسلات والمخزون الحالي." : "Sales, views, saves, active carts, and current stock."}</p></div></div>{report.products.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{locale === "ar" ? "المنتج" : "Product"}</th><th>SKU</th><th>{locale === "ar" ? "مبيع" : "Sold"}</th><th>{locale === "ar" ? "الإيراد" : "Revenue"}</th><th>{locale === "ar" ? "مشاهدات" : "Views"}</th><th>{locale === "ar" ? "أمنيات" : "Wishlists"}</th><th>{locale === "ar" ? "في السلات" : "In carts"}</th><th>{locale === "ar" ? "المخزون" : "Stock"}</th></tr></thead><tbody>{report.products.map((product) => <tr key={product.id}><td className={styles.primaryCell}>{localizedText(locale, product.nameAr, product.nameEn)}</td><td dir="ltr">{product.sku}</td><td>{product.units}</td><td>{formatMoney(product.revenue, locale, currency)}</td><td>{product.views}</td><td>{product.wishlists}</td><td>{product.cartAdds}</td><td>{product.stock}</td></tr>)}</tbody></table></div> : <EmptyState>{locale === "ar" ? "لا توجد بيانات منتجات ضمن الفترة." : "No product data for this period."}</EmptyState>}</section>
    <section className={`${styles.grid} ${styles.metrics} ${styles.sectionGap}`} aria-label={locale === "ar" ? "مؤشرات المنتجات" : "Product report signals"}><MetricCard label={locale === "ar" ? "الأكثر مبيعًا" : "Best selling"} value={productName(byUnits[0])} hint={byUnits[0] ? `${byUnits[0].units} ${locale === "ar" ? "وحدة" : "units"}` : undefined} /><MetricCard label={locale === "ar" ? "الأقل مبيعًا" : "Least selling"} value={productName(byUnits.at(-1))} hint={byUnits.at(-1) ? `${byUnits.at(-1)!.units} ${locale === "ar" ? "وحدة" : "units"}` : undefined} /><MetricCard label={locale === "ar" ? "الأكثر مشاهدة" : "Most viewed"} value={productName(byViews[0])} hint={byViews[0] ? String(byViews[0].views) : undefined} /><MetricCard label={locale === "ar" ? "الأكثر حفظًا" : "Most wishlisted"} value={productName(byWishlists[0])} hint={byWishlists[0] ? String(byWishlists[0].wishlists) : undefined} /><MetricCard label={locale === "ar" ? "الأكثر إضافة للسلات" : "Most added to carts"} value={productName(byCarts[0])} hint={byCarts[0] ? String(byCarts[0].cartAdds) : undefined} /><MetricCard label={locale === "ar" ? "في السلات دون طلب" : "In carts, not ordered"} value={productName(cartNotOrdered)} tone={cartNotOrdered ? "warning" : "default"} /><MetricCard label={locale === "ar" ? "مخزون منخفض" : "Low stock"} value={String(lowStock)} tone={lowStock ? "warning" : "default"} /><MetricCard label={locale === "ar" ? "نفد المخزون" : "Out of stock"} value={String(outOfStock)} tone={outOfStock ? "danger" : "default"} /></section>
    <section className={`${styles.grid} ${styles.twoColumn} ${styles.sectionGap}`}><article className={styles.card}><div className={styles.cardHeader}><div><h2>{words.categories}</h2></div></div>{report.categories.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{locale === "ar" ? "التصنيف" : "Category"}</th><th>{locale === "ar" ? "الوحدات" : "Units"}</th><th>{locale === "ar" ? "الإيراد" : "Revenue"}</th></tr></thead><tbody>{report.categories.map((category) => <tr key={category.id}><td>{localizedText(locale, category.nameAr, category.nameEn)}</td><td>{category.units}</td><td>{formatMoney(category.revenue, locale, currency)}</td></tr>)}</tbody></table></div> : <EmptyState>{locale === "ar" ? "لا توجد مبيعات تصنيفات." : "No category sales."}</EmptyState>}</article>
      <article className={styles.card}><div className={styles.cardHeader}><div><h2>{words.insights}</h2><p>{locale === "ar" ? "تظهر فقط عندما تكفي البيانات." : "Shown only when enough data exists."}</p></div></div>{report.insights.length ? <ul className={styles.statusList}>{report.insights.map((insight) => <li className={styles.statusRow} key={insight.key}><span><strong>{locale === "ar" ? insight.titleAr : insight.titleEn}</strong><span className={styles.secondaryText}>{locale === "ar" ? insight.detailAr : insight.detailEn}</span></span></li>)}</ul> : <EmptyState>{locale === "ar" ? "لا تكفي البيانات بعد لاستخلاص مؤشرات مفيدة." : "There is not enough data for useful insights yet."}</EmptyState>}</article></section>
    <section className={`${styles.card} ${styles.sectionGap}`}><div className={styles.cardHeader}><div><h2>{words.customerReport}</h2></div></div>{report.customers.length ? <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{locale === "ar" ? "العميل" : "Customer"}</th><th>{locale === "ar" ? "المدينة" : "City"}</th><th>{locale === "ar" ? "التسجيل" : "Joined"}</th><th>{locale === "ar" ? "الطلبات" : "Orders"}</th><th>{locale === "ar" ? "الإنفاق" : "Spending"}</th><th>{locale === "ar" ? "آخر طلب" : "Last order"}</th><th>{locale === "ar" ? "النوع" : "Type"}</th><th>{locale === "ar" ? "التفاصيل" : "Details"}</th></tr></thead><tbody>{report.customers.map((customer) => { const inactive = !customer.lastOrderAt || Date.parse(customer.lastOrderAt) < inactiveCutoff; return <tr key={customer.id}><td className={styles.primaryCell}>{customer.name}<span className={styles.secondaryText} dir="ltr">{customer.email}</span><span className={styles.secondaryText} dir="ltr">{customer.phone}</span></td><td>{localizedText(locale, customer.cityAr, customer.cityEn)}</td><td>{formatAdminDate(customer.joinedAt, locale)}</td><td>{customer.orderCount}</td><td>{formatMoney(customer.spending, locale, currency)}</td><td>{customer.lastOrderAt ? formatAdminDate(customer.lastOrderAt, locale) : "—"}</td><td>{inactive ? (locale === "ar" ? "غير نشط" : "Inactive") : customer.orderCount > 1 ? (locale === "ar" ? "عائد" : "Returning") : (locale === "ar" ? "جديد" : "New")}</td><td><Link className={styles.buttonSecondary} href={`/${locale}/admin/customers/${customer.id}`}>{locale === "ar" ? "عرض" : "View"}</Link></td></tr>; })}</tbody></table></div> : <EmptyState>{locale === "ar" ? "لا يوجد عملاء مسجلون." : "No registered customers."}</EmptyState>}</section>
  </>;
}
