import Link from "next/link";
import { AdminPagination, EmptyState, PageHeader, StatusBadge, adminStyles as styles, statusTone } from "@/components/admin/AdminUi";
import { formatAdminDate, formatMoney } from "@/lib/admin/format";
import { adminStatusLabel, getAdminLocale } from "@/lib/admin/i18n";
import { listOrders } from "@/lib/admin/repository";

type Query = { page?: string; search?: string; status?: string; paymentStatus?: string; fulfillment?: string; from?: string; to?: string };
export default async function OrdersPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<Query> }) {
  const locale = getAdminLocale((await params).locale); const query = await searchParams; const orders = await listOrders({ ...query, page: Number(query.page || 1) });
  const hrefFor = (page: number) => { const values = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value && key !== "page") values.set(key, value); }); values.set("page", String(page)); return `?${values}`; };
  const statuses = ["NEW", "CONFIRMED", "PREPARING", "READY_FOR_DELIVERY", "SENT_TO_DELIVERY_COMPANY", "DELIVERED", "READY_FOR_PICKUP", "COLLECTED", "CANCELLED"];
  return <><PageHeader title={locale === "ar" ? "الطلبات" : "Orders"} description={locale === "ar" ? "ابحث وصفِّ الطلبات، ثم افتح الطلب لتحديث حالته أو طباعته." : "Search and filter orders, then open one to update its state or print it."} />
    <form className={styles.toolbar} method="get" role="search"><div className={`${styles.field} ${styles.fieldGrow}`}><label htmlFor="order-search">{locale === "ar" ? "بحث" : "Search"}</label><input id="order-search" className={styles.input} name="search" defaultValue={query.search} placeholder={locale === "ar" ? "رقم الطلب أو العميل أو الهاتف أو البريد" : "Order number, customer, phone, or email"} /></div><FilterSelect name="status" label={locale === "ar" ? "حالة الطلب" : "Order status"} value={query.status} options={statuses.map((status) => [status, adminStatusLabel(locale, status)])} all={locale === "ar" ? "كل الحالات" : "All statuses"} /><FilterSelect name="paymentStatus" label={locale === "ar" ? "الدفع" : "Payment"} value={query.paymentStatus} options={[["PENDING", adminStatusLabel(locale, "PENDING")], ["PAID", adminStatusLabel(locale, "PAID")], ["CANCELLED", adminStatusLabel(locale, "CANCELLED")]]} all={locale === "ar" ? "كل حالات الدفع" : "All payment states"} /><FilterSelect name="fulfillment" label={locale === "ar" ? "الاستلام" : "Fulfillment"} value={query.fulfillment} options={[["DELIVERY", locale === "ar" ? "توصيل" : "Delivery"], ["PICKUP", locale === "ar" ? "استلام من المتجر" : "Pickup"]]} all={locale === "ar" ? "كل الطرق" : "All methods"} /><div className={styles.field}><label htmlFor="from">{locale === "ar" ? "من" : "From"}</label><input id="from" className={styles.input} type="date" name="from" defaultValue={query.from} /></div><div className={styles.field}><label htmlFor="to">{locale === "ar" ? "إلى" : "To"}</label><input id="to" className={styles.input} type="date" name="to" defaultValue={query.to} /></div><button className={styles.button} type="submit">{locale === "ar" ? "تصفية" : "Filter"}</button><Link className={styles.buttonSecondary} href={`/${locale}/admin/orders`}>{locale === "ar" ? "مسح" : "Clear"}</Link></form>
    <div className={styles.tableWrap}>{orders.items.length ? <table className={styles.table}><thead><tr><th>{locale === "ar" ? "الطلب" : "Order"}</th><th>{locale === "ar" ? "العميل" : "Customer"}</th><th>{locale === "ar" ? "الاستلام" : "Fulfillment"}</th><th>{locale === "ar" ? "المبلغ" : "Amount"}</th><th>{locale === "ar" ? "حالة الطلب" : "Order status"}</th><th>{locale === "ar" ? "الدفع" : "Payment"}</th><th>{locale === "ar" ? "الإجراء" : "Action"}</th></tr></thead><tbody>{orders.items.map((order) => <tr key={order.id}><td className={styles.primaryCell}>{order.orderNumber}<span className={styles.secondaryText}>{formatAdminDate(order.createdAt, locale, true)}</span></td><td>{order.customerName}<span className={styles.secondaryText} dir="ltr">{order.customerPhone}</span></td><td>{order.fulfillmentMethod === "DELIVERY" ? (locale === "ar" ? "توصيل" : "Delivery") : (locale === "ar" ? "استلام" : "Pickup")}</td><td className={styles.numeric}>{formatMoney(order.total, locale, order.currency)}</td><td><StatusBadge label={adminStatusLabel(locale, order.status)} tone={statusTone(order.status)} /></td><td><StatusBadge label={adminStatusLabel(locale, order.paymentStatus)} tone={statusTone(order.paymentStatus)} /></td><td><Link className={styles.buttonSecondary} href={`/${locale}/admin/orders/${order.id}`}>{locale === "ar" ? "عرض" : "View"}</Link></td></tr>)}</tbody></table> : <EmptyState>{locale === "ar" ? "لا توجد طلبات مطابقة." : "No orders match these filters."}</EmptyState>}</div>
    <AdminPagination locale={locale} page={orders.page} pageCount={orders.pageCount} total={orders.total} hrefFor={hrefFor} label={locale === "ar" ? "صفحات الطلبات" : "Order pages"} previous={locale === "ar" ? "السابق" : "Previous"} next={locale === "ar" ? "التالي" : "Next"} pageLabel={locale === "ar" ? "صفحة" : "Page"} />
  </>;
}

function FilterSelect({ name, label, value, options, all }: { name: string; label: string; value?: string; options: Array<readonly [string, string]>; all: string }) { return <div className={styles.field}><label htmlFor={`filter-${name}`}>{label}</label><select id={`filter-${name}`} className={styles.select} name={name} defaultValue={value ?? "ALL"}><option value="ALL">{all}</option>{options.map(([key, text]) => <option value={key} key={key}>{text}</option>)}</select></div>; }
