import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Banknote, Boxes, Headphones, MapPin } from "lucide-react";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/config";
import { translate } from "@/lib/i18n/dictionaries";
import { getStorefrontHomeCatalog } from "@/lib/catalog/server";
import { getHomepageContent } from "@/lib/i18n/content";
import { buttonStyles } from "@/components/ui/button";
import { ProductGrid } from "@/components/storefront/product-grid";
import { CategoryGrid } from "@/components/storefront/category-grid";

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; if (!isLocale(raw)) notFound(); const locale = raw; const t = (key: string) => translate(locale, key);
  const [catalog, homepage] = await Promise.all([getStorefrontHomeCatalog(), getHomepageContent(locale)]);
  const heroTitle = homepage?.title ?? (locale === "ar" ? "إعدادات المتجر غير متاحة" : "Storefront settings unavailable");
  const heroBody = homepage?.body ?? (locale === "ar" ? "تعذر تحميل محتوى المتجر من قاعدة البيانات. حاول لاحقاً." : "Store content could not be loaded from the database. Please try later.");
  const heroImage = homepage?.imageUrl?.startsWith("/") ? homepage.imageUrl : "/images/jys-hero.png";
  const exploreHref = `/${locale}/categories`;
  return <>
    <section className="container-shell pt-5 md:pt-7"><div className="relative min-h-[35rem] overflow-hidden rounded-[2rem] bg-[#191817] shadow-lift md:min-h-[40rem]"><Image src={heroImage} alt={t("home.heroAlt")} fill priority sizes="(max-width: 1440px) 100vw, 1408px" className="object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(0,0,0,.24),transparent_27%,transparent_72%,rgba(0,0,0,.28)),linear-gradient(180deg,rgba(0,0,0,.1),rgba(0,0,0,.08)_55%,rgba(0,0,0,.45))]" /><div className="relative z-10 mx-auto flex min-h-[35rem] max-w-xl flex-col items-center px-5 pb-10 pt-14 text-center text-white md:min-h-[40rem] md:pt-20"><p className="mb-5 text-xs font-black uppercase tracking-[.3em] text-[#e1aa78]">{t("home.eyebrow")}</p><h1 className="text-balance font-display text-5xl font-semibold leading-[.98] drop-shadow-lg sm:text-6xl md:text-7xl">{heroTitle}</h1><p className="mt-6 max-w-lg text-pretty text-base leading-7 text-white/90 md:text-lg">{heroBody}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={`/${locale}/products`} className={buttonStyles({ size: "lg", className: "bg-white text-brand-strong hover:bg-[#f3e9dd]" })}>{t("common.shopNow")}<ArrowUpRight className="size-4 rtl:-scale-x-100" /></Link><Link href={exploreHref} className={buttonStyles({ variant: "secondary", size: "lg", className: "border-white/25 bg-black/20 text-white backdrop-blur hover:bg-white/10" })}>{t("common.explore")}</Link></div><p className="mt-auto inline-flex items-center gap-2 rounded-full border border-white/25 bg-black/30 px-4 py-2 text-xs font-semibold text-white/85 backdrop-blur"><Banknote className="size-4 text-[#e1aa78]" />{t("home.heroNote")}</p></div></div></section>
    {catalog.source === "unavailable" ? <section className="container-shell pt-6"><div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm font-semibold text-red-900">{locale === "ar" ? "تعذر تحميل المنتجات والأسعار والمخزون من قاعدة البيانات. لم نعرض كتالوجاً احتياطياً." : "Products, prices and stock could not be loaded from the database. No fallback catalogue was shown."}</div></section> : null}
    <section className="container-shell py-8"><div className="grid divide-y divide-line rounded-2xl border border-line bg-surface md:grid-cols-3 md:divide-x md:divide-y-0 rtl:md:divide-x-reverse">{[[Banknote,"benefit.cash","benefit.cashText"],[Boxes,"benefit.stock","benefit.stockText"],[Headphones,"benefit.support","benefit.supportText"]].map(([Icon,title,text], index) => { const I = Icon as typeof Banknote; return <div key={index} className="flex items-center gap-4 p-5 md:p-6"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-brand-strong text-white"><I className="size-5" /></span><div><h2 className="font-bold">{t(title as string)}</h2><p className="text-sm text-muted">{t(text as string)}</p></div></div>; })}</div></section>
    <section className="container-shell py-16"><header className="mb-8 flex items-end justify-between gap-5"><div><p className="mb-2 text-xs font-black uppercase tracking-[.22em] text-accent">{t("home.editLabel")}</p><h2 className="font-display text-3xl font-semibold md:text-5xl">{t("home.featured")}</h2><p className="mt-3 text-muted">{t("home.featuredText")}</p></div><Link href={`/${locale}/products`} className="hidden text-sm font-black underline decoration-accent/40 underline-offset-8 hover:text-accent sm:block">{t("common.viewAll")}</Link></header><ProductGrid products={catalog.products} locale={locale} headingLevel={3} /><Link href={`/${locale}/products`} className={buttonStyles({ variant: "secondary", className: "mt-7 w-full sm:hidden" })}>{t("common.viewAll")}</Link></section>
    <section className="bg-[#ded7cb] py-16"><div className="container-shell"><header className="mb-8 max-w-xl"><h2 className="font-display text-3xl font-semibold md:text-5xl">{t("home.categories")}</h2><p className="mt-3 text-muted">{t("home.categoriesText")}</p></header><CategoryGrid locale={locale} categories={catalog.categories} /></div></section>
    <section className="container-shell grid gap-5 py-20 lg:grid-cols-[1.15fr_.85fr]"><div className="surface-grid rounded-3xl border border-line bg-surface p-8 md:p-12"><p className="mb-4 text-xs font-black uppercase tracking-[.22em] text-accent">{t("home.standardLabel")}</p><h2 className="max-w-xl font-display text-4xl font-semibold md:text-5xl">{t("home.storyTitle")}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-muted">{t("home.storyText")}</p><Link href={`/${locale}/products`} className={buttonStyles({ className: "mt-8" })}>{t("common.explore")}<ArrowUpRight className="size-4 rtl:-scale-x-100" /></Link></div><div className="relative overflow-hidden rounded-3xl bg-accent p-8 text-white md:p-12"><MapPin className="absolute -bottom-14 -end-10 size-64 stroke-[.5] text-white/10" /><div className="relative"><p className="mb-4 text-xs font-black uppercase tracking-[.22em] text-white/80">{t("home.marketLabel")}</p><h2 className="font-display text-4xl font-semibold">{t("home.deliveryTitle")}</h2><p className="mt-5 text-white/85">{t("home.deliveryText")}</p><div className="mt-8 flex gap-3"><Link href={`/${locale}/delivery`} className={buttonStyles({ variant: "secondary", className: "border-white/20 bg-white text-brand-strong" })}>{t("nav.delivery")}</Link><Link href={`/${locale}/pickup`} className={buttonStyles({ variant: "quiet", className: "text-white hover:bg-white/10" })}>{t("nav.pickup")}</Link></div></div></div></section>
  </>;
}
